# Generated by Django 4.2 on 2026-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('government', 'Government Official'), ('admin', 'Administrator')], default='citizen', max_length=20),
        ),
    ]
