# Generated by Django 5.2 on 2025-04-14 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('defense', 'Defense'), ('agriculture', 'Agriculture'), ('welfare', 'Social Welfare'), ('other', 'Other')], max_length=50)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='fund_allocations/')),
            ],
        ),
    ]
