# Generated by Django 5.2 on 2025-04-19 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundallocation',
            options={'ordering': ['-allocation_date'], 'verbose_name_plural': 'Fund Allocations'},
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='fundallocation',
            name='allocation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundallocation',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='fund_allocations/%Y/%m/%d/'),
        ),
    ]
